version: '3'

services:
  mongo:
    # network_mode: host
    image: mongo
    restart: "no"
    #entrypoint: /nats-server --name srvcargo -js 
    #entrypoint: /nats-server -js --name srvcargo -m 8222 
    #entrypoint: /nats-server -js --name srvcargo -m 8222 -DV
    #entrypoint: /nats-server -js --name srvcargo -DV
    # restart: always
    ports: 
       - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    # network_mode: host
    restart: "no"
    depends_on:
      - "mongo"
    ports:
      - 6800:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: "mongo"
#      ME_CONFIG_MONGODB_PORT: 12345
      
# docker run --rm -e ME_CONFIG_MONGODB_SERVER=localhost -e ME_CONFIG_MONGODB_ADMINUSERNAME=admin -e ME_CONFIG_MONGODB_ADMINPASSWORD=secret mongo-express
