version: '3'

services:
  web:
    image: nginx
    volumes:
    - ./.templates:/etc/nginx/templates
    - ./.etc/nginx:/etc/nginx/
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  registry:
    # restart: always
    image: registry:2
    # ports:
    # - "5002:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      #REGISTRY_HTTP_TLS_CERTIFICATE: /cert/auth.crt
      #REGISTRY_HTTP_TLS_KEY: /cert/auth-no.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./.auth:/auth
      - ./.data:/data
      - ./.cert:/cert

